### ISSUE TITLE
Consider dropping in Picnic CSS for a bit of basic styling

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/fishbiz-map#8]
https://picnicss.com

I believe that if this is done within the scope of the App component it cannot pollute the global CSS space (so long as `scoped` is checked); it's easy/light enough to get a little decoration without being too much.  (It's not crucial that this app match identically the styling of the FishBiz site itself 100%; some differences in buttons / table formatting is ok!)

**Comment by cstephen** [comment]
I ended up using Picnic CSS inspired Sass code because Picnic CSS turned out to be too invasive and messed up the Leaflet map by scattering map tiles all over the page.
